/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.planoEnsino.planoensinotaidiego;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int android=0x7f020000;
        public static final int cancelar=0x7f020001;
        public static final int excluir=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int limpar=0x7f020004;
        public static final int novo=0x7f020005;
        public static final int pesquisar=0x7f020006;
        public static final int sair=0x7f020007;
        public static final int salvar=0x7f020008;
    }
    public static final class id {
        public static final int btBuscar=0x7f050002;
        public static final int btCancelar=0x7f050007;
        public static final int btExcluir=0x7f050009;
        public static final int btSalvar=0x7f050008;
        public static final int campoProfessor=0x7f050004;
        public static final int campoConteudo=0x7f050006;
        public static final int campoMateria=0x7f050001;
        public static final int professor=0x7f05000b;
        public static final int conteudo=0x7f05000c;
        public static final int materia=0x7f05000a;
        public static final int text1=0x7f050000;
        public static final int text2=0x7f050003;
        public static final int text3=0x7f050005;
    }
    public static final class layout {
        public static final int form_buscar_plano=0x7f030000;
        public static final int form_editar_plano=0x7f030001;
        public static final int plano_linha_tabela=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
